### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by penguoir** [penguoir/use-firebase#1]
Docs right now aren't up to standard.

### Todo
- [ ] Create a documentation website on GitHub pages
- [ ] Add more examples of usage
- [ ] Automatic creation with gulp
